python/Flasky/app_blog/models.py
from datetime import datetime

from markdown import markdown
import bleach
from flask import url_for
from flask_sqlalchemy import SQLAlchemy
from wtforms import ValidationError


db = SQLAlchemy()


class Article(db.Model):

    __tablename__ = 'article'

    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.Text)
    body = db.Column(db.Text)
    body_markdown = db.Column(db.Text)
    vote = db.Column(db.Integer, default=0)
    watch = db.Column(db.Integer, default=0)
    timestamp = db.Column(db.DateTime, index=True,
                          default=datetime.utcnow)

    @staticmethod
    def on_changed_body(target, value, oldvalue, initiator):
        allowed_tags = ['a', 'abbr', 'acronym', 'b', 'blockquote', 'code',
                        'em', 'i', 'li', 'ol', 'pre', 'strong', 'ul',
                        'h1', 'h2', 'h3', 'p', 'img']
        target.body_html = bleach.linkify(bleach.clean(
            markdown(value, output_format='html'),
            tags=allowed_tags, strip=True))

    def to_json(self):
        json_post = {
            'url': url_for('api.get_post', id=self.id, _external=True),
            'title': self.title,
            'body': self.body,
            'body_html': self.body_html,
            'timestamp': self.timestamp,
            'author': url_for('api.get_user', id=self.author_id,
                              _external=True),
            'comments': url_for('api.get_post_comments', id=self.id,
                                _external=True),
            'comment_count': self.comments.count()
        }
        return json_post

    @staticmethod
    def from_json(json_post):
        body = json_post.get('body')
        if body is None or body == '':
            raise ValidationError('post does not have a body')
        return Article(body=body)


db.event.listen(Article.body, 'set', Article.on_changed_body)

python/Flasky/app_blog/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField
from wtforms.validators import DataRequired, Length


class ArticleForm(FlaskForm):
    title = StringField('Title', validators=[DataRequired('Title Required'), Length(0, 128)])
    body = TextAreaField('Body', validators=[DataRequired('Empty Body')])
    submit = SubmitField('Submit')

python/Flasky/app_blog/__init__.py
#!usr/bin/env python
# -*- coding:utf-8 -*-


from flask import Flask
from flask_bootstrap import Bootstrap
from flask_moment import Moment
from flask_admin import Admin
from flask_debugtoolbar import DebugToolbarExtension

from config import config


bootstrap = Bootstrap()
moment = Moment()
toolbar = DebugToolbarExtension()
admin = Admin(name='Blog')


def create_blog(config_name):

    # init app
    blog = Flask(__name__)
    blog.config.from_object(config[config_name])
    config[config_name].init_app(blog)

    from app_blog.models import db
    db.init_app(blog)

    bootstrap.init_app(blog)
    moment.init_app(blog)
    toolbar.init_app(blog)

    # background administrator
    from flask_admin.contrib.sqla import ModelView
    from app_blog.models import Article
    admin.init_app(blog)
    admin.add_view(ModelView(Article, db.session))

    # Blueprint
    from .main import main as main_blueprint
    blog.register_blueprint(main_blueprint)

    return blog

python/Flasky/app_blog/main/__init__.py
from flask import Blueprint

main = Blueprint('main', __name__)

from . import views, forms

python/Flasky/app_blog/main/views.py
from flask import render_template
from . import main
from app_blog.models import Article


# Home page --- Articles
@main.route('/', methods=['POST', 'GET'])
def index():
    articles = Article.query.order_by(Article.timestamp.desc())
    return render_template('index.html', articles=articles)


# Article page
@main.route('/article/<int:article_id>', methods=['GET', 'POST'])
def article(article_id):
    the_article = Article.query.get_or_404(article_id)
    return render_template('article.html', the_article=the_article)


# About me page
@main.route('/me')
def me():
    return render_template('me.html')

python/Flasky/app_blog/templates/article.html
{% extends "base.html" %}

{% block content %}

<div class="container">
    <h3>
        <div style="text-align:center;"><p>{{ the_article.title }}</p></div>
    </h3>
    <hr/>
    <div><p>{{ the_article.body_markdown }}</p></div>
    <hr/>
    <div style="text-align: right"> Read: {{ the_article.watch }} Vote: {{ the_article.vote }}</div>
</div>

{% endblock %}

python/Flasky/app_blog/templates/base.html
{% extends "bootstrap/base.html" %}

{% block title %}KnD{% endblock %}

{% block head %}
{{ super() }}
<script src="//cdn.ckeditor.com/4.6.2/basic/ckeditor.js"></script>
<link rel="shortcut icon" href="{{ url_for('static', filename='images/Favicon.ico') }}" type="image/x-icon">
{% endblock %}

{% block navbar %}
<div class="navbar navbar-default" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{{ url_for('main.index') }}">Kings Never Die</a>
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav navbar-right">
                <li class="active">
                    <a href="{{ url_for('main.index') }}">博客</a>
                </li>
                <li>
                    <a href="https://github.com/Arszrc">Github</a>
                </li>
                <li>
                    <a href="https://www.zhihu.com/people/Arszrc">知乎</a>
                </li>
                <li>
                    <a href="{{ url_for('main.me') }}">关于我</a>
                </li>
            </ul>
        </div>
    </div>
</div>
{% endblock %}

<div class="container">
    {% block content %}
    {% endblock %}
</div>


{% block scripts %}
{{ super() }}
{{ moment.include_moment() }}
{% endblock %}

python/Flasky/app_blog/templates/index.html
{% extends "base.html" %}

{% block content %}

<div class="container">
    {% for article in articles %}
         <div><a href="{{ url_for('main.article', article_id=article.id) }}">{{ article.title }}</a></div><hr/>
    {% endfor %}
</div>
    
{% endblock %}

python/Flasky/app_blog/templates/me.html
{% extends "base.html" %}